#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_AIA")]
	public partial class DtClsDB_AIADataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_m_setting_aplikasi(tbl_m_setting_aplikasi instance);
    partial void Updatetbl_m_setting_aplikasi(tbl_m_setting_aplikasi instance);
    partial void Deletetbl_m_setting_aplikasi(tbl_m_setting_aplikasi instance);
    partial void Inserttbl_t_konseling_fatigue(tbl_t_konseling_fatigue instance);
    partial void Updatetbl_t_konseling_fatigue(tbl_t_konseling_fatigue instance);
    partial void Deletetbl_t_konseling_fatigue(tbl_t_konseling_fatigue instance);
    partial void Inserttbl_m_user_login(tbl_m_user_login instance);
    partial void Updatetbl_m_user_login(tbl_m_user_login instance);
    partial void Deletetbl_m_user_login(tbl_m_user_login instance);
    partial void Inserttbl_r_alasan_fatigue(tbl_r_alasan_fatigue instance);
    partial void Updatetbl_r_alasan_fatigue(tbl_r_alasan_fatigue instance);
    partial void Deletetbl_r_alasan_fatigue(tbl_r_alasan_fatigue instance);
    partial void Inserttbl_r_dept(tbl_r_dept instance);
    partial void Updatetbl_r_dept(tbl_r_dept instance);
    partial void Deletetbl_r_dept(tbl_r_dept instance);
    partial void Inserttbl_r_kategori_user(tbl_r_kategori_user instance);
    partial void Updatetbl_r_kategori_user(tbl_r_kategori_user instance);
    partial void Deletetbl_r_kategori_user(tbl_r_kategori_user instance);
    partial void Inserttbl_r_menu(tbl_r_menu instance);
    partial void Updatetbl_r_menu(tbl_r_menu instance);
    partial void Deletetbl_r_menu(tbl_r_menu instance);
    partial void Inserttbl_r_next_followup(tbl_r_next_followup instance);
    partial void Updatetbl_r_next_followup(tbl_r_next_followup instance);
    partial void Deletetbl_r_next_followup(tbl_r_next_followup instance);
    partial void Inserttbl_r_status_sanksi(tbl_r_status_sanksi instance);
    partial void Updatetbl_r_status_sanksi(tbl_r_status_sanksi instance);
    partial void Deletetbl_r_status_sanksi(tbl_r_status_sanksi instance);
    #endregion
		
		public DtClsDB_AIADataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_AIAConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DtClsDB_AIADataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DtClsDB_AIADataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DtClsDB_AIADataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DtClsDB_AIADataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_m_setting_aplikasi> tbl_m_setting_aplikasis
		{
			get
			{
				return this.GetTable<tbl_m_setting_aplikasi>();
			}
		}
		
		public System.Data.Linq.Table<tbl_t_konseling_fatigue> tbl_t_konseling_fatigues
		{
			get
			{
				return this.GetTable<tbl_t_konseling_fatigue>();
			}
		}
		
		public System.Data.Linq.Table<tbl_m_user_login> tbl_m_user_logins
		{
			get
			{
				return this.GetTable<tbl_m_user_login>();
			}
		}
		
		public System.Data.Linq.Table<tbl_operator_fatigue_need_followup> tbl_operator_fatigue_need_followups
		{
			get
			{
				return this.GetTable<tbl_operator_fatigue_need_followup>();
			}
		}
		
		public System.Data.Linq.Table<tbl_r_alasan_fatigue> tbl_r_alasan_fatigues
		{
			get
			{
				return this.GetTable<tbl_r_alasan_fatigue>();
			}
		}
		
		public System.Data.Linq.Table<tbl_r_dept> tbl_r_depts
		{
			get
			{
				return this.GetTable<tbl_r_dept>();
			}
		}
		
		public System.Data.Linq.Table<tbl_r_kategori_user> tbl_r_kategori_users
		{
			get
			{
				return this.GetTable<tbl_r_kategori_user>();
			}
		}
		
		public System.Data.Linq.Table<tbl_r_menu> tbl_r_menus
		{
			get
			{
				return this.GetTable<tbl_r_menu>();
			}
		}
		
		public System.Data.Linq.Table<tbl_r_next_followup> tbl_r_next_followups
		{
			get
			{
				return this.GetTable<tbl_r_next_followup>();
			}
		}
		
		public System.Data.Linq.Table<tbl_r_status_sanksi> tbl_r_status_sanksis
		{
			get
			{
				return this.GetTable<tbl_r_status_sanksi>();
			}
		}
		
		public System.Data.Linq.Table<vw_history_followup_operator_fatigue> vw_history_followup_operator_fatigues
		{
			get
			{
				return this.GetTable<vw_history_followup_operator_fatigue>();
			}
		}
		
		public System.Data.Linq.Table<vw_t_user_kategori> vw_t_user_kategoris
		{
			get
			{
				return this.GetTable<vw_t_user_kategori>();
			}
		}
		
		public System.Data.Linq.Table<vw_operator_fatigue_need_followup> vw_operator_fatigue_need_followups
		{
			get
			{
				return this.GetTable<vw_operator_fatigue_need_followup>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_m_setting_aplikasi")]
	public partial class tbl_m_setting_aplikasi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nama;
		
		private string _description;
		
		private string _icon;
		
		private string _theme;
		
		private string _insert_by;
		
		private string _ip;
		
		private string _created_at;
		
		private string _updated_at;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OniconChanging(string value);
    partial void OniconChanged();
    partial void OnthemeChanging(string value);
    partial void OnthemeChanged();
    partial void Oninsert_byChanging(string value);
    partial void Oninsert_byChanged();
    partial void OnipChanging(string value);
    partial void OnipChanged();
    partial void Oncreated_atChanging(string value);
    partial void Oncreated_atChanged();
    partial void Onupdated_atChanging(string value);
    partial void Onupdated_atChanged();
    #endregion
		
		public tbl_m_setting_aplikasi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(50)")]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_icon", DbType="VarChar(50)")]
		public string icon
		{
			get
			{
				return this._icon;
			}
			set
			{
				if ((this._icon != value))
				{
					this.OniconChanging(value);
					this.SendPropertyChanging();
					this._icon = value;
					this.SendPropertyChanged("icon");
					this.OniconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_theme", DbType="VarChar(50)")]
		public string theme
		{
			get
			{
				return this._theme;
			}
			set
			{
				if ((this._theme != value))
				{
					this.OnthemeChanging(value);
					this.SendPropertyChanging();
					this._theme = value;
					this.SendPropertyChanged("theme");
					this.OnthemeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_by", DbType="VarChar(50)")]
		public string insert_by
		{
			get
			{
				return this._insert_by;
			}
			set
			{
				if ((this._insert_by != value))
				{
					this.Oninsert_byChanging(value);
					this.SendPropertyChanging();
					this._insert_by = value;
					this.SendPropertyChanged("insert_by");
					this.Oninsert_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip", DbType="VarChar(50)")]
		public string ip
		{
			get
			{
				return this._ip;
			}
			set
			{
				if ((this._ip != value))
				{
					this.OnipChanging(value);
					this.SendPropertyChanging();
					this._ip = value;
					this.SendPropertyChanged("ip");
					this.OnipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="VarChar(50)")]
		public string created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="VarChar(50)")]
		public string updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_t_konseling_fatigue")]
	public partial class tbl_t_konseling_fatigue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _pid;
		
		private System.Nullable<System.DateTime> _tanggal;
		
		private string _nrp;
		
		private string _Jam_tidur;
		
		private System.Nullable<int> _is_minumobat;
		
		private System.Nullable<int> _is_masalah;
		
		private string _Status_ftw;
		
		private string _ftw_via;
		
		private string _Kategory_problem_fatigue;
		
		private string _remarksCNC;
		
		private string _Next_action;
		
		private System.Nullable<int> _Status_akumulasi;
		
		private string _Status_CNC;
		
		private string _Komitment;
		
		private string _CNC_by;
		
		private System.Nullable<System.DateTime> _CNC_date;
		
		private System.Nullable<int> _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpidChanging(string value);
    partial void OnpidChanged();
    partial void OntanggalChanging(System.Nullable<System.DateTime> value);
    partial void OntanggalChanged();
    partial void OnnrpChanging(string value);
    partial void OnnrpChanged();
    partial void OnJam_tidurChanging(string value);
    partial void OnJam_tidurChanged();
    partial void Onis_minumobatChanging(System.Nullable<int> value);
    partial void Onis_minumobatChanged();
    partial void Onis_masalahChanging(System.Nullable<int> value);
    partial void Onis_masalahChanged();
    partial void OnStatus_ftwChanging(string value);
    partial void OnStatus_ftwChanged();
    partial void Onftw_viaChanging(string value);
    partial void Onftw_viaChanged();
    partial void OnKategory_problem_fatigueChanging(string value);
    partial void OnKategory_problem_fatigueChanged();
    partial void OnremarksCNCChanging(string value);
    partial void OnremarksCNCChanged();
    partial void OnNext_actionChanging(string value);
    partial void OnNext_actionChanged();
    partial void OnStatus_akumulasiChanging(System.Nullable<int> value);
    partial void OnStatus_akumulasiChanged();
    partial void OnStatus_CNCChanging(string value);
    partial void OnStatus_CNCChanged();
    partial void OnKomitmentChanging(string value);
    partial void OnKomitmentChanged();
    partial void OnCNC_byChanging(string value);
    partial void OnCNC_byChanged();
    partial void OnCNC_dateChanging(System.Nullable<System.DateTime> value);
    partial void OnCNC_dateChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    #endregion
		
		public tbl_t_konseling_fatigue()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string pid
		{
			get
			{
				return this._pid;
			}
			set
			{
				if ((this._pid != value))
				{
					this.OnpidChanging(value);
					this.SendPropertyChanging();
					this._pid = value;
					this.SendPropertyChanged("pid");
					this.OnpidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal", DbType="Date")]
		public System.Nullable<System.DateTime> tanggal
		{
			get
			{
				return this._tanggal;
			}
			set
			{
				if ((this._tanggal != value))
				{
					this.OntanggalChanging(value);
					this.SendPropertyChanging();
					this._tanggal = value;
					this.SendPropertyChanged("tanggal");
					this.OntanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrp", DbType="VarChar(15)")]
		public string nrp
		{
			get
			{
				return this._nrp;
			}
			set
			{
				if ((this._nrp != value))
				{
					this.OnnrpChanging(value);
					this.SendPropertyChanging();
					this._nrp = value;
					this.SendPropertyChanged("nrp");
					this.OnnrpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jam_tidur", DbType="VarChar(25)")]
		public string Jam_tidur
		{
			get
			{
				return this._Jam_tidur;
			}
			set
			{
				if ((this._Jam_tidur != value))
				{
					this.OnJam_tidurChanging(value);
					this.SendPropertyChanging();
					this._Jam_tidur = value;
					this.SendPropertyChanged("Jam_tidur");
					this.OnJam_tidurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_minumobat", DbType="Int")]
		public System.Nullable<int> is_minumobat
		{
			get
			{
				return this._is_minumobat;
			}
			set
			{
				if ((this._is_minumobat != value))
				{
					this.Onis_minumobatChanging(value);
					this.SendPropertyChanging();
					this._is_minumobat = value;
					this.SendPropertyChanged("is_minumobat");
					this.Onis_minumobatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_masalah", DbType="Int")]
		public System.Nullable<int> is_masalah
		{
			get
			{
				return this._is_masalah;
			}
			set
			{
				if ((this._is_masalah != value))
				{
					this.Onis_masalahChanging(value);
					this.SendPropertyChanging();
					this._is_masalah = value;
					this.SendPropertyChanged("is_masalah");
					this.Onis_masalahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status_ftw", DbType="VarChar(50)")]
		public string Status_ftw
		{
			get
			{
				return this._Status_ftw;
			}
			set
			{
				if ((this._Status_ftw != value))
				{
					this.OnStatus_ftwChanging(value);
					this.SendPropertyChanging();
					this._Status_ftw = value;
					this.SendPropertyChanged("Status_ftw");
					this.OnStatus_ftwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ftw_via", DbType="VarChar(100)")]
		public string ftw_via
		{
			get
			{
				return this._ftw_via;
			}
			set
			{
				if ((this._ftw_via != value))
				{
					this.Onftw_viaChanging(value);
					this.SendPropertyChanging();
					this._ftw_via = value;
					this.SendPropertyChanged("ftw_via");
					this.Onftw_viaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kategory_problem_fatigue", DbType="VarChar(25)")]
		public string Kategory_problem_fatigue
		{
			get
			{
				return this._Kategory_problem_fatigue;
			}
			set
			{
				if ((this._Kategory_problem_fatigue != value))
				{
					this.OnKategory_problem_fatigueChanging(value);
					this.SendPropertyChanging();
					this._Kategory_problem_fatigue = value;
					this.SendPropertyChanged("Kategory_problem_fatigue");
					this.OnKategory_problem_fatigueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remarksCNC", DbType="VarChar(100)")]
		public string remarksCNC
		{
			get
			{
				return this._remarksCNC;
			}
			set
			{
				if ((this._remarksCNC != value))
				{
					this.OnremarksCNCChanging(value);
					this.SendPropertyChanging();
					this._remarksCNC = value;
					this.SendPropertyChanged("remarksCNC");
					this.OnremarksCNCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Next_action", DbType="VarChar(25)")]
		public string Next_action
		{
			get
			{
				return this._Next_action;
			}
			set
			{
				if ((this._Next_action != value))
				{
					this.OnNext_actionChanging(value);
					this.SendPropertyChanging();
					this._Next_action = value;
					this.SendPropertyChanged("Next_action");
					this.OnNext_actionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status_akumulasi", DbType="Int")]
		public System.Nullable<int> Status_akumulasi
		{
			get
			{
				return this._Status_akumulasi;
			}
			set
			{
				if ((this._Status_akumulasi != value))
				{
					this.OnStatus_akumulasiChanging(value);
					this.SendPropertyChanging();
					this._Status_akumulasi = value;
					this.SendPropertyChanged("Status_akumulasi");
					this.OnStatus_akumulasiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status_CNC", DbType="VarChar(50)")]
		public string Status_CNC
		{
			get
			{
				return this._Status_CNC;
			}
			set
			{
				if ((this._Status_CNC != value))
				{
					this.OnStatus_CNCChanging(value);
					this.SendPropertyChanging();
					this._Status_CNC = value;
					this.SendPropertyChanged("Status_CNC");
					this.OnStatus_CNCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Komitment", DbType="VarChar(100)")]
		public string Komitment
		{
			get
			{
				return this._Komitment;
			}
			set
			{
				if ((this._Komitment != value))
				{
					this.OnKomitmentChanging(value);
					this.SendPropertyChanging();
					this._Komitment = value;
					this.SendPropertyChanged("Komitment");
					this.OnKomitmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNC_by", DbType="VarChar(25)")]
		public string CNC_by
		{
			get
			{
				return this._CNC_by;
			}
			set
			{
				if ((this._CNC_by != value))
				{
					this.OnCNC_byChanging(value);
					this.SendPropertyChanging();
					this._CNC_by = value;
					this.SendPropertyChanged("CNC_by");
					this.OnCNC_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNC_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> CNC_date
		{
			get
			{
				return this._CNC_date;
			}
			set
			{
				if ((this._CNC_date != value))
				{
					this.OnCNC_dateChanging(value);
					this.SendPropertyChanging();
					this._CNC_date = value;
					this.SendPropertyChanged("CNC_date");
					this.OnCNC_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_m_user_login")]
	public partial class tbl_m_user_login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _kategori_user_id;
		
		private string _dept_code;
		
		private string _nrp;
		
		private string _password;
		
		private string _nama;
		
		private string _insert_by;
		
		private string _ip;
		
		private string _created_at;
		
		private string _updated_at;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onkategori_user_idChanging(string value);
    partial void Onkategori_user_idChanged();
    partial void Ondept_codeChanging(string value);
    partial void Ondept_codeChanged();
    partial void OnnrpChanging(string value);
    partial void OnnrpChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void Oninsert_byChanging(string value);
    partial void Oninsert_byChanged();
    partial void OnipChanging(string value);
    partial void OnipChanged();
    partial void Oncreated_atChanging(string value);
    partial void Oncreated_atChanged();
    partial void Onupdated_atChanging(string value);
    partial void Onupdated_atChanged();
    #endregion
		
		public tbl_m_user_login()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kategori_user_id", DbType="VarChar(50)")]
		public string kategori_user_id
		{
			get
			{
				return this._kategori_user_id;
			}
			set
			{
				if ((this._kategori_user_id != value))
				{
					this.Onkategori_user_idChanging(value);
					this.SendPropertyChanging();
					this._kategori_user_id = value;
					this.SendPropertyChanged("kategori_user_id");
					this.Onkategori_user_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dept_code", DbType="VarChar(50)")]
		public string dept_code
		{
			get
			{
				return this._dept_code;
			}
			set
			{
				if ((this._dept_code != value))
				{
					this.Ondept_codeChanging(value);
					this.SendPropertyChanging();
					this._dept_code = value;
					this.SendPropertyChanged("dept_code");
					this.Ondept_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrp", DbType="VarChar(50)")]
		public string nrp
		{
			get
			{
				return this._nrp;
			}
			set
			{
				if ((this._nrp != value))
				{
					this.OnnrpChanging(value);
					this.SendPropertyChanging();
					this._nrp = value;
					this.SendPropertyChanged("nrp");
					this.OnnrpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(50)")]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_by", DbType="VarChar(50)")]
		public string insert_by
		{
			get
			{
				return this._insert_by;
			}
			set
			{
				if ((this._insert_by != value))
				{
					this.Oninsert_byChanging(value);
					this.SendPropertyChanging();
					this._insert_by = value;
					this.SendPropertyChanged("insert_by");
					this.Oninsert_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip", DbType="VarChar(50)")]
		public string ip
		{
			get
			{
				return this._ip;
			}
			set
			{
				if ((this._ip != value))
				{
					this.OnipChanging(value);
					this.SendPropertyChanging();
					this._ip = value;
					this.SendPropertyChanged("ip");
					this.OnipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="VarChar(50)")]
		public string created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="VarChar(50)")]
		public string updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_operator_fatigue_need_followup")]
	public partial class tbl_operator_fatigue_need_followup
	{
		
		private string _pid;
		
		private System.Nullable<System.DateTime> _tanggal;
		
		private string _nrp;
		
		private string _nama;
		
		private string _Departemen;
		
		private string _unit;
		
		private string _jamtidur;
		
		private string _jaminput;
		
		private System.Nullable<bool> _is_minumoabt;
		
		private System.Nullable<bool> _is_masalah;
		
		private string _statusfatigue;
		
		private string _ftw_result;
		
		private string _created_by;
		
		public tbl_operator_fatigue_need_followup()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", DbType="NVarChar(255)")]
		public string pid
		{
			get
			{
				return this._pid;
			}
			set
			{
				if ((this._pid != value))
				{
					this._pid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal", DbType="Date")]
		public System.Nullable<System.DateTime> tanggal
		{
			get
			{
				return this._tanggal;
			}
			set
			{
				if ((this._tanggal != value))
				{
					this._tanggal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrp", DbType="NVarChar(255)")]
		public string nrp
		{
			get
			{
				return this._nrp;
			}
			set
			{
				if ((this._nrp != value))
				{
					this._nrp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="NVarChar(255)")]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this._nama = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departemen", DbType="NVarChar(255)")]
		public string Departemen
		{
			get
			{
				return this._Departemen;
			}
			set
			{
				if ((this._Departemen != value))
				{
					this._Departemen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unit", DbType="NVarChar(255)")]
		public string unit
		{
			get
			{
				return this._unit;
			}
			set
			{
				if ((this._unit != value))
				{
					this._unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jamtidur", DbType="VarChar(50)")]
		public string jamtidur
		{
			get
			{
				return this._jamtidur;
			}
			set
			{
				if ((this._jamtidur != value))
				{
					this._jamtidur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jaminput", DbType="VarChar(50)")]
		public string jaminput
		{
			get
			{
				return this._jaminput;
			}
			set
			{
				if ((this._jaminput != value))
				{
					this._jaminput = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_minumoabt", DbType="Bit")]
		public System.Nullable<bool> is_minumoabt
		{
			get
			{
				return this._is_minumoabt;
			}
			set
			{
				if ((this._is_minumoabt != value))
				{
					this._is_minumoabt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_masalah", DbType="Bit")]
		public System.Nullable<bool> is_masalah
		{
			get
			{
				return this._is_masalah;
			}
			set
			{
				if ((this._is_masalah != value))
				{
					this._is_masalah = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusfatigue", DbType="NVarChar(255)")]
		public string statusfatigue
		{
			get
			{
				return this._statusfatigue;
			}
			set
			{
				if ((this._statusfatigue != value))
				{
					this._statusfatigue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ftw_result", DbType="NVarChar(255)")]
		public string ftw_result
		{
			get
			{
				return this._ftw_result;
			}
			set
			{
				if ((this._ftw_result != value))
				{
					this._ftw_result = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="NVarChar(255)")]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this._created_by = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_r_alasan_fatigue")]
	public partial class tbl_r_alasan_fatigue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _remarks;
		
		private string _kategory;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnremarksChanging(string value);
    partial void OnremarksChanged();
    partial void OnkategoryChanging(string value);
    partial void OnkategoryChanged();
    #endregion
		
		public tbl_r_alasan_fatigue()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remarks", DbType="VarChar(50)")]
		public string remarks
		{
			get
			{
				return this._remarks;
			}
			set
			{
				if ((this._remarks != value))
				{
					this.OnremarksChanging(value);
					this.SendPropertyChanging();
					this._remarks = value;
					this.SendPropertyChanged("remarks");
					this.OnremarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kategory", DbType="VarChar(25)")]
		public string kategory
		{
			get
			{
				return this._kategory;
			}
			set
			{
				if ((this._kategory != value))
				{
					this.OnkategoryChanging(value);
					this.SendPropertyChanging();
					this._kategory = value;
					this.SendPropertyChanged("kategory");
					this.OnkategoryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_r_dept")]
	public partial class tbl_r_dept : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _dept_code;
		
		private string _departemen;
		
		private string _insert_by;
		
		private string _ip;
		
		private string _created_at;
		
		private string _updated_at;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Ondept_codeChanging(string value);
    partial void Ondept_codeChanged();
    partial void OndepartemenChanging(string value);
    partial void OndepartemenChanged();
    partial void Oninsert_byChanging(string value);
    partial void Oninsert_byChanged();
    partial void OnipChanging(string value);
    partial void OnipChanged();
    partial void Oncreated_atChanging(string value);
    partial void Oncreated_atChanged();
    partial void Onupdated_atChanging(string value);
    partial void Onupdated_atChanged();
    #endregion
		
		public tbl_r_dept()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dept_code", DbType="VarChar(50)")]
		public string dept_code
		{
			get
			{
				return this._dept_code;
			}
			set
			{
				if ((this._dept_code != value))
				{
					this.Ondept_codeChanging(value);
					this.SendPropertyChanging();
					this._dept_code = value;
					this.SendPropertyChanged("dept_code");
					this.Ondept_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departemen", DbType="VarChar(50)")]
		public string departemen
		{
			get
			{
				return this._departemen;
			}
			set
			{
				if ((this._departemen != value))
				{
					this.OndepartemenChanging(value);
					this.SendPropertyChanging();
					this._departemen = value;
					this.SendPropertyChanged("departemen");
					this.OndepartemenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_by", DbType="VarChar(50)")]
		public string insert_by
		{
			get
			{
				return this._insert_by;
			}
			set
			{
				if ((this._insert_by != value))
				{
					this.Oninsert_byChanging(value);
					this.SendPropertyChanging();
					this._insert_by = value;
					this.SendPropertyChanged("insert_by");
					this.Oninsert_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip", DbType="VarChar(50)")]
		public string ip
		{
			get
			{
				return this._ip;
			}
			set
			{
				if ((this._ip != value))
				{
					this.OnipChanging(value);
					this.SendPropertyChanging();
					this._ip = value;
					this.SendPropertyChanged("ip");
					this.OnipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="VarChar(50)")]
		public string created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="VarChar(50)")]
		public string updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_r_kategori_user")]
	public partial class tbl_r_kategori_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _kategori;
		
		private string _login_controller;
		
		private string _login_function;
		
		private string _insert_by;
		
		private string _ip;
		
		private string _created_at;
		
		private string _updated_at;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnkategoriChanging(string value);
    partial void OnkategoriChanged();
    partial void Onlogin_controllerChanging(string value);
    partial void Onlogin_controllerChanged();
    partial void Onlogin_functionChanging(string value);
    partial void Onlogin_functionChanged();
    partial void Oninsert_byChanging(string value);
    partial void Oninsert_byChanged();
    partial void OnipChanging(string value);
    partial void OnipChanged();
    partial void Oncreated_atChanging(string value);
    partial void Oncreated_atChanged();
    partial void Onupdated_atChanging(string value);
    partial void Onupdated_atChanged();
    #endregion
		
		public tbl_r_kategori_user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kategori", DbType="VarChar(50)")]
		public string kategori
		{
			get
			{
				return this._kategori;
			}
			set
			{
				if ((this._kategori != value))
				{
					this.OnkategoriChanging(value);
					this.SendPropertyChanging();
					this._kategori = value;
					this.SendPropertyChanged("kategori");
					this.OnkategoriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login_controller", DbType="VarChar(50)")]
		public string login_controller
		{
			get
			{
				return this._login_controller;
			}
			set
			{
				if ((this._login_controller != value))
				{
					this.Onlogin_controllerChanging(value);
					this.SendPropertyChanging();
					this._login_controller = value;
					this.SendPropertyChanged("login_controller");
					this.Onlogin_controllerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login_function", DbType="VarChar(50)")]
		public string login_function
		{
			get
			{
				return this._login_function;
			}
			set
			{
				if ((this._login_function != value))
				{
					this.Onlogin_functionChanging(value);
					this.SendPropertyChanging();
					this._login_function = value;
					this.SendPropertyChanged("login_function");
					this.Onlogin_functionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_by", DbType="VarChar(50)")]
		public string insert_by
		{
			get
			{
				return this._insert_by;
			}
			set
			{
				if ((this._insert_by != value))
				{
					this.Oninsert_byChanging(value);
					this.SendPropertyChanging();
					this._insert_by = value;
					this.SendPropertyChanged("insert_by");
					this.Oninsert_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip", DbType="VarChar(50)")]
		public string ip
		{
			get
			{
				return this._ip;
			}
			set
			{
				if ((this._ip != value))
				{
					this.OnipChanging(value);
					this.SendPropertyChanging();
					this._ip = value;
					this.SendPropertyChanged("ip");
					this.OnipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="VarChar(50)")]
		public string created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="VarChar(50)")]
		public string updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_r_menu")]
	public partial class tbl_r_menu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _kategori_user_id;
		
		private string _title;
		
		private string _type;
		
		private string _link_controller;
		
		private string _link_function;
		
		private string _hidden;
		
		private string _new_tab;
		
		private string _insert_by;
		
		private string _ip;
		
		private string _created_at;
		
		private string _updated_at;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onkategori_user_idChanging(string value);
    partial void Onkategori_user_idChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void Onlink_controllerChanging(string value);
    partial void Onlink_controllerChanged();
    partial void Onlink_functionChanging(string value);
    partial void Onlink_functionChanged();
    partial void OnhiddenChanging(string value);
    partial void OnhiddenChanged();
    partial void Onnew_tabChanging(string value);
    partial void Onnew_tabChanged();
    partial void Oninsert_byChanging(string value);
    partial void Oninsert_byChanged();
    partial void OnipChanging(string value);
    partial void OnipChanged();
    partial void Oncreated_atChanging(string value);
    partial void Oncreated_atChanged();
    partial void Onupdated_atChanging(string value);
    partial void Onupdated_atChanged();
    #endregion
		
		public tbl_r_menu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kategori_user_id", DbType="VarChar(50)")]
		public string kategori_user_id
		{
			get
			{
				return this._kategori_user_id;
			}
			set
			{
				if ((this._kategori_user_id != value))
				{
					this.Onkategori_user_idChanging(value);
					this.SendPropertyChanging();
					this._kategori_user_id = value;
					this.SendPropertyChanged("kategori_user_id");
					this.Onkategori_user_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(50)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link_controller", DbType="VarChar(50)")]
		public string link_controller
		{
			get
			{
				return this._link_controller;
			}
			set
			{
				if ((this._link_controller != value))
				{
					this.Onlink_controllerChanging(value);
					this.SendPropertyChanging();
					this._link_controller = value;
					this.SendPropertyChanged("link_controller");
					this.Onlink_controllerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link_function", DbType="VarChar(50)")]
		public string link_function
		{
			get
			{
				return this._link_function;
			}
			set
			{
				if ((this._link_function != value))
				{
					this.Onlink_functionChanging(value);
					this.SendPropertyChanging();
					this._link_function = value;
					this.SendPropertyChanged("link_function");
					this.Onlink_functionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hidden", DbType="VarChar(50)")]
		public string hidden
		{
			get
			{
				return this._hidden;
			}
			set
			{
				if ((this._hidden != value))
				{
					this.OnhiddenChanging(value);
					this.SendPropertyChanging();
					this._hidden = value;
					this.SendPropertyChanged("hidden");
					this.OnhiddenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_new_tab", DbType="VarChar(50)")]
		public string new_tab
		{
			get
			{
				return this._new_tab;
			}
			set
			{
				if ((this._new_tab != value))
				{
					this.Onnew_tabChanging(value);
					this.SendPropertyChanging();
					this._new_tab = value;
					this.SendPropertyChanged("new_tab");
					this.Onnew_tabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_by", DbType="VarChar(50)")]
		public string insert_by
		{
			get
			{
				return this._insert_by;
			}
			set
			{
				if ((this._insert_by != value))
				{
					this.Oninsert_byChanging(value);
					this.SendPropertyChanging();
					this._insert_by = value;
					this.SendPropertyChanged("insert_by");
					this.Oninsert_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip", DbType="VarChar(50)")]
		public string ip
		{
			get
			{
				return this._ip;
			}
			set
			{
				if ((this._ip != value))
				{
					this.OnipChanging(value);
					this.SendPropertyChanging();
					this._ip = value;
					this.SendPropertyChanged("ip");
					this.OnipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="VarChar(50)")]
		public string created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="VarChar(50)")]
		public string updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_r_next_followup")]
	public partial class tbl_r_next_followup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _next_followup;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onnext_followupChanging(string value);
    partial void Onnext_followupChanged();
    #endregion
		
		public tbl_r_next_followup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_next_followup", DbType="VarChar(25)")]
		public string next_followup
		{
			get
			{
				return this._next_followup;
			}
			set
			{
				if ((this._next_followup != value))
				{
					this.Onnext_followupChanging(value);
					this.SendPropertyChanging();
					this._next_followup = value;
					this.SendPropertyChanged("next_followup");
					this.Onnext_followupChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_r_status_sanksi")]
	public partial class tbl_r_status_sanksi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _status_sanksi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onstatus_sanksiChanging(string value);
    partial void Onstatus_sanksiChanged();
    #endregion
		
		public tbl_r_status_sanksi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_sanksi", DbType="VarChar(25)")]
		public string status_sanksi
		{
			get
			{
				return this._status_sanksi;
			}
			set
			{
				if ((this._status_sanksi != value))
				{
					this.Onstatus_sanksiChanging(value);
					this.SendPropertyChanging();
					this._status_sanksi = value;
					this.SendPropertyChanged("status_sanksi");
					this.Onstatus_sanksiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_history_followup_operator_fatigue")]
	public partial class vw_history_followup_operator_fatigue
	{
		
		private System.Nullable<System.Guid> _pid;
		
		private string _tanggal;
		
		private string _nrp;
		
		private string _Nama;
		
		private string _Departemen;
		
		private string _unit;
		
		private string _jamtidur;
		
		private string _jaminput;
		
		private System.Nullable<int> _is_minumobat;
		
		private System.Nullable<int> _is_masalah;
		
		private string _Status_ftw;
		
		private string _ftw_via;
		
		private string _Kategory_problem_fatigue;
		
		private string _remarksCNC;
		
		private string _Next_action;
		
		private System.Nullable<int> _Status_akumulasi;
		
		private string _Status_CNC;
		
		private string _Komitment;
		
		private string _CNC_by;
		
		private System.Nullable<System.DateTime> _CNC_date;
		
		private System.Nullable<int> _status;
		
		private string _CNC_Name;
		
		private string _Status_ftw_site;
		
		public vw_history_followup_operator_fatigue()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> pid
		{
			get
			{
				return this._pid;
			}
			set
			{
				if ((this._pid != value))
				{
					this._pid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal", DbType="NVarChar(50)")]
		public string tanggal
		{
			get
			{
				return this._tanggal;
			}
			set
			{
				if ((this._tanggal != value))
				{
					this._tanggal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrp", DbType="NVarChar(50)")]
		public string nrp
		{
			get
			{
				return this._nrp;
			}
			set
			{
				if ((this._nrp != value))
				{
					this._nrp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama", DbType="VarChar(201)")]
		public string Nama
		{
			get
			{
				return this._Nama;
			}
			set
			{
				if ((this._Nama != value))
				{
					this._Nama = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departemen", DbType="VarChar(10)")]
		public string Departemen
		{
			get
			{
				return this._Departemen;
			}
			set
			{
				if ((this._Departemen != value))
				{
					this._Departemen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unit", DbType="VarChar(100)")]
		public string unit
		{
			get
			{
				return this._unit;
			}
			set
			{
				if ((this._unit != value))
				{
					this._unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jamtidur", DbType="VarChar(71)")]
		public string jamtidur
		{
			get
			{
				return this._jamtidur;
			}
			set
			{
				if ((this._jamtidur != value))
				{
					this._jamtidur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jaminput", DbType="VarChar(30)")]
		public string jaminput
		{
			get
			{
				return this._jaminput;
			}
			set
			{
				if ((this._jaminput != value))
				{
					this._jaminput = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_minumobat", DbType="Int")]
		public System.Nullable<int> is_minumobat
		{
			get
			{
				return this._is_minumobat;
			}
			set
			{
				if ((this._is_minumobat != value))
				{
					this._is_minumobat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_masalah", DbType="Int")]
		public System.Nullable<int> is_masalah
		{
			get
			{
				return this._is_masalah;
			}
			set
			{
				if ((this._is_masalah != value))
				{
					this._is_masalah = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status_ftw", DbType="VarChar(50)")]
		public string Status_ftw
		{
			get
			{
				return this._Status_ftw;
			}
			set
			{
				if ((this._Status_ftw != value))
				{
					this._Status_ftw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ftw_via", DbType="VarChar(100)")]
		public string ftw_via
		{
			get
			{
				return this._ftw_via;
			}
			set
			{
				if ((this._ftw_via != value))
				{
					this._ftw_via = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kategory_problem_fatigue", DbType="VarChar(25)")]
		public string Kategory_problem_fatigue
		{
			get
			{
				return this._Kategory_problem_fatigue;
			}
			set
			{
				if ((this._Kategory_problem_fatigue != value))
				{
					this._Kategory_problem_fatigue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remarksCNC", DbType="VarChar(100)")]
		public string remarksCNC
		{
			get
			{
				return this._remarksCNC;
			}
			set
			{
				if ((this._remarksCNC != value))
				{
					this._remarksCNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Next_action", DbType="VarChar(25)")]
		public string Next_action
		{
			get
			{
				return this._Next_action;
			}
			set
			{
				if ((this._Next_action != value))
				{
					this._Next_action = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status_akumulasi", DbType="Int")]
		public System.Nullable<int> Status_akumulasi
		{
			get
			{
				return this._Status_akumulasi;
			}
			set
			{
				if ((this._Status_akumulasi != value))
				{
					this._Status_akumulasi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status_CNC", DbType="VarChar(50)")]
		public string Status_CNC
		{
			get
			{
				return this._Status_CNC;
			}
			set
			{
				if ((this._Status_CNC != value))
				{
					this._Status_CNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Komitment", DbType="VarChar(100)")]
		public string Komitment
		{
			get
			{
				return this._Komitment;
			}
			set
			{
				if ((this._Komitment != value))
				{
					this._Komitment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNC_by", DbType="VarChar(25)")]
		public string CNC_by
		{
			get
			{
				return this._CNC_by;
			}
			set
			{
				if ((this._CNC_by != value))
				{
					this._CNC_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNC_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> CNC_date
		{
			get
			{
				return this._CNC_date;
			}
			set
			{
				if ((this._CNC_date != value))
				{
					this._CNC_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNC_Name", DbType="VarChar(100)")]
		public string CNC_Name
		{
			get
			{
				return this._CNC_Name;
			}
			set
			{
				if ((this._CNC_Name != value))
				{
					this._CNC_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status_ftw_site", DbType="VarChar(50)")]
		public string Status_ftw_site
		{
			get
			{
				return this._Status_ftw_site;
			}
			set
			{
				if ((this._Status_ftw_site != value))
				{
					this._Status_ftw_site = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_t_user_kategori")]
	public partial class vw_t_user_kategori
	{
		
		private string _nrp;
		
		private string _nama;
		
		private string _kategori_user_id;
		
		private string _dept_code;
		
		private string _login_controller;
		
		private string _login_function;
		
		public vw_t_user_kategori()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrp", DbType="VarChar(50)")]
		public string nrp
		{
			get
			{
				return this._nrp;
			}
			set
			{
				if ((this._nrp != value))
				{
					this._nrp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(50)")]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this._nama = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kategori_user_id", DbType="VarChar(50)")]
		public string kategori_user_id
		{
			get
			{
				return this._kategori_user_id;
			}
			set
			{
				if ((this._kategori_user_id != value))
				{
					this._kategori_user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dept_code", DbType="VarChar(50)")]
		public string dept_code
		{
			get
			{
				return this._dept_code;
			}
			set
			{
				if ((this._dept_code != value))
				{
					this._dept_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login_controller", DbType="VarChar(50)")]
		public string login_controller
		{
			get
			{
				return this._login_controller;
			}
			set
			{
				if ((this._login_controller != value))
				{
					this._login_controller = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login_function", DbType="VarChar(50)")]
		public string login_function
		{
			get
			{
				return this._login_function;
			}
			set
			{
				if ((this._login_function != value))
				{
					this._login_function = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_operator_fatigue_need_followup")]
	public partial class vw_operator_fatigue_need_followup
	{
		
		private System.Nullable<System.Guid> _pid;
		
		private string _tanggal;
		
		private string _nrp;
		
		private string _Nama;
		
		private string _Departemen;
		
		private string _unit;
		
		private string _jamtidur;
		
		private string _jaminput;
		
		private int _is_minumoabt;
		
		private int _is_masalah;
		
		private string _statusfatigue;
		
		private string _ftw_result;
		
		private string _created_by;
		
		public vw_operator_fatigue_need_followup()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> pid
		{
			get
			{
				return this._pid;
			}
			set
			{
				if ((this._pid != value))
				{
					this._pid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal", DbType="NVarChar(50)")]
		public string tanggal
		{
			get
			{
				return this._tanggal;
			}
			set
			{
				if ((this._tanggal != value))
				{
					this._tanggal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrp", DbType="NVarChar(50)")]
		public string nrp
		{
			get
			{
				return this._nrp;
			}
			set
			{
				if ((this._nrp != value))
				{
					this._nrp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama", DbType="VarChar(201)")]
		public string Nama
		{
			get
			{
				return this._Nama;
			}
			set
			{
				if ((this._Nama != value))
				{
					this._Nama = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departemen", DbType="VarChar(10)")]
		public string Departemen
		{
			get
			{
				return this._Departemen;
			}
			set
			{
				if ((this._Departemen != value))
				{
					this._Departemen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unit", DbType="VarChar(100)")]
		public string unit
		{
			get
			{
				return this._unit;
			}
			set
			{
				if ((this._unit != value))
				{
					this._unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jamtidur", DbType="VarChar(71)")]
		public string jamtidur
		{
			get
			{
				return this._jamtidur;
			}
			set
			{
				if ((this._jamtidur != value))
				{
					this._jamtidur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jaminput", DbType="VarChar(30)")]
		public string jaminput
		{
			get
			{
				return this._jaminput;
			}
			set
			{
				if ((this._jaminput != value))
				{
					this._jaminput = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_minumoabt", DbType="Int NOT NULL")]
		public int is_minumoabt
		{
			get
			{
				return this._is_minumoabt;
			}
			set
			{
				if ((this._is_minumoabt != value))
				{
					this._is_minumoabt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_masalah", DbType="Int NOT NULL")]
		public int is_masalah
		{
			get
			{
				return this._is_masalah;
			}
			set
			{
				if ((this._is_masalah != value))
				{
					this._is_masalah = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusfatigue", DbType="VarChar(16)")]
		public string statusfatigue
		{
			get
			{
				return this._statusfatigue;
			}
			set
			{
				if ((this._statusfatigue != value))
				{
					this._statusfatigue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ftw_result", DbType="VarChar(9)")]
		public string ftw_result
		{
			get
			{
				return this._ftw_result;
			}
			set
			{
				if ((this._ftw_result != value))
				{
					this._ftw_result = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this._created_by = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
